image: python:latest

stages:
  - Test
  - Release

pypi:
    stage: Release
    script:
        - pip install -U twine
        - python setup.py sdist
        - twine upload dist/*
    only:
        - tags

test:
  stage: Test
  image: $IMAGE
  parallel:
    matrix:
      - IMAGE: ["python:3.6", "python:3.7"]
  script:
    - pip install -e .
    - pip install pytest bagit-create==0.1
    - INDICO_KEY="$INDICO_KEY" python -m pytest --junitxml=path
  artifacts:
    when: always
    reports:
      junit: ./report.xml

